@startuml sequence_connexion
actor Conducteur as C
participant "IHM : connexion.html" as UI
participant "SystemeAuthentification" as SYS
participant "Modele " as BDD

C -> UI : saisir email + mot de passe
UI -> SYS : seConnecter(email, motDePasse)
SYS -> BDD : rechercherParEmail(email)
activate BDD
BDD --> SYS : utilisateur
deactivate BDD

SYS -> SYS : verifierMotDePasse()

alt identifiants valides
    SYS --> UI : sessionCreee(utilisateur)
    UI --> C : redirection vers "Mes trajets"
else identifiants invalides
    SYS --> UI : erreurAuthentification
    UI --> C : afficher message d'erreur
end
@enduml